_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 64
criterion:
    value: MSE
dropout:
    value: 0.4
epochs:
    value: 20
hidden_size:
    value: 18
learning_rate:
    value: 0.0005
momentum:
    value:
        - 0.9
        - 0.92
num_layers:
    value: 4
optimizer:
    value: Adam
sequence_length:
    value: 15
weight_decay:
    value: 1e-05
